version: '2.4'

services:
    db:
        image: postgres:12.4-alpine
        container_name: postgres
        restart: always
        environment:
            TZ: America/Sao_Paulo
            POSTGRES_DB: rent_movies
            POSTGRES_USER: root
            POSTGRES_PASSWORD: secret
        ports:
            - 5432:5432
        volumes:
            - ./data:/var/lib/postgresql/data
